# -*- coding: utf-8 -*-
"""DSA_PROJECT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xLGCrYqvA0nqVbGh2zXbXu8xb9cLZwWN
"""

from collections import deque   #Library
import random     #generates random no.
import datetime   #used to print date and time


class Queue:      #Class of Queue
    def __init__(self):
        self.buffer = deque()
    def enque(self, val):     #Adds element in queue
        self.buffer.appendleft(val)
    def deque(self):            #Removes last element from queue
      if len(self.buffer)==0:
        print("Queue is empty.")
        return
      return self.buffer.pop()
    def is_empty(self):         #Returns True if queue is empty
      return len(self.buffer)==0
    def length(self):                 #Returns the lenght of the queue
      return len(self.buffer)
    def ret(self, i):                 #Returns the value stored at the given index in queue
      return self.buffer[i]
    def front(self):                  #Returns first element in the queue
      return self.buffer[-1]
    def last(self):                   #Returns last element of the queue
      return self.buffer[0]

      
      #OBJECTS
queue1 = Queue()    #Queue1 for storing NAMES of Orders
queue2 = Queue()    #Queue2 for storing QUANTITY of Orders
queue3 = Queue()    #Queue3 for storing PRICES of Orders
queue4 = Queue()    #Queue4 for storing FINAL PRICE of Orders


def exit():     #Ends / Exits the program
  print("\t\t\t*-*-*-Thank You !!!-*-*-*")
  print("\t\t\t\tExited.")


def check():    #Prints orders in Queue
  
  print("\n\t\t\t*-*-*-*-Order Queue-*-*-*-*\n")
  print("Queue=> ", queue1.buffer, "\n")      #Prints Order in FIFO order

def payment():    #Prints the payment of the orders
  list1=[23456787,5363788,63575777,4353889,8299665,12564789]

    
  print("\n")
  print('                                                                   \\\||||///               ')
  print('                                                                     ( o o )')
  print('                                                      |----ooO---------(_)------------------|')
  print('                                                      |                                     |')
  print('                                                      |         Welcome to Restaurent       |')
  print('                                                      |            Hello World!             |')
  print('                                                      |                                     |')
  print('                                                      |------------------------------Ooo----|')
  print('                                                                    |__| |__|               ')
  print('                                                                     ||   ||                ')
  print('                                                                    oooO   Oooo              ')
  print('\n')
  print('\n')
  print('******************************************************************************************************************************************')
  print('\n')
  print('                                                             PAYMENT_RECEIPT                                        ')
  print('\n')
  print('                                                         "Hello World!" RESTAURENT      ')

  print('                                                SHOP__NO.11,TRD FLR,SOUTH FOOD COURT,GIGA MALL')
  print('                                                           STORE ID:343536375')
  print('                                                          RAWALPINDI-43600,PUNJAB')
  print('                                                         www."Hello World!".com')
  print('                                                         Facebook: \"Hello World!"')
  print('                                                           0300-XXXXXX-1')
  print('                                                          UAN : 111-ABC(436676)')
  print('\n')
  print('******************************************************************************************************************************************')
  Token = random.choice(list1)          #generates random numbers from list
  date = datetime.datetime.now()      #Stores date and time
  print("Invoice :",Token)
  print("Date and Time :",date)
  print('+--------------------+---------------------------------------+------------------+---------------------------------+----------------------+')
  print('|   SERIAL NO        |   ITEMS                               |       QUANTITY   |           ACTUAL RATE           |     AMOUNT          |         ')
  print('+--------------------+---------------------------------------+------------------+---------------------------------+----------------------+')
  amount = 0    #calculates total bill
  item = 0      #calculates the total item (total quantity)
  n = queue1.length()
  sno = 1   #Serial No.
  for i in range(n):    
    amount += queue4.ret(i)     #Adds the total Prices
    item += queue2.ret(i)       #Adds the total Quantities

    print("     ",sno,"\t\t",queue1.ret(i) , "\t\t\t\t\t", queue2.ret(i), "\t\t\t", queue3.ret(i), "\t\t\t", queue4.ret(i))
    sno += 1    #serial no increases

  print('\n')
  print('+----------------------------------------------------------------------------------------------------------------------------------------+') 
  print('\n')
  service = 100.25        #Service Taxes
  total = service + amount      #Calculates final bill
  
  print("                       Total Items                                                                         ", item, "\n" )    #Prints Total Items
  print("                         Amount                                                                            ", amount )
  print('                      Service Tax                                                                          ', service )
  print("                                                                                                      -----------------")
  print('                       Total Bill                                                                          ', total )
  print("                                                                                                      -----------------")
  print("                                                                                                      -----------------")
  print("\n")
  print('------------------------------------------------------------------------------------------------------------------------------------------')
  print('------------------------------------------------------------------------------------------------------------------------------------------')
  print('\n')   
  print("                                       *******************THANK YOU VISIT US AGAIN**********************                      ")
  print('\n')
  print("                                                  ********EAT AS MUCH AS YOU LIKE!!***********                               ")
  print('\n')
  print('------------------------------------------------------------------------------------------------------------------------------------------')
  print('------------------------------------------------------------------------------------------------------------------------------------------')


def Menu():   #Menu Func

  print("\t\t\t*-*-*-*-Menu-*-*-*-*")     #Displays Menu
  print("\t1. Pizza")
  print("\t2. Burgers")
  print("\t3. Fries")
  print("\t4. Desserts")
  print("\t5. Drinks")
  print("\t6. Check Cart")
  print("\t7. Payment")
  print("\t0. EXIT")
  ch = int(input("Enter Choice : "))
  return ch

while True:
  ch = Menu()
  if ch == 1:     #PIZZA
    pizza = "Pizza"
    def Menu1():
      print("\t\t\t*-*-*-*-Pizza Menu-*-*-*-*")
      print("\t1. Fajita")
      print("\t2. Tikka")
      print("\t3. Cheese")
      print("\t4. Special")
      ch1 = int(input("Enter Choice : "))
      return ch1
    while True:
      ch1 = Menu1()
      if ch1 == 1:
        flav = "Fajita"
        def Menu2():
          print("\t\t\t*-*-*-*-Pizza Size-*-*-*-*")
          print("\t1. Small (400)")
          print("\t2. Medium (800)")
          print("\t3. Large (1200)")
          ch2 = int(input("Enter Choice : "))
          return ch2
        while True:
          ch2 = Menu2()
          if ch2 == 1:
            quan = int(input("Enter Quantity : "))
            s = "Small"   #Size
            p = 400 
            fp = p * quan      #Final prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", pizza, ":", flav, s, "\t=>Price:", fp, "\n")
            name = "Fajita S P"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
          elif ch2 == 2:
            quan = int(input("Enter Quantity : "))
            s = "Medium"   #Size
            p = 800
            fp = p * quan     #Final Prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", pizza, ":", flav, s, "\t=>Price:", fp, "\n")
            name = "Fajita Med P"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
          elif ch2 == 3:
            quan = int(input("Enter Quantity : "))
            s = "Large"   #Size
            p = 1200 
            fp = p * quan      #Final Prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", pizza, ":", flav, s, "\t=>Price:", fp, "\n")
            name = "Fajita L P"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
        break

      elif ch1 == 2:
        flav = "Tikka"
        def Menu2():
          print("\t\t\t*-*-*-*-Pizza Size-*-*-*-*")
          print("\t1. Small (420)")
          print("\t2. Medium (840)")
          print("\t3. Large (1190)")
          ch2 = int(input("Enter Choice : "))
          return ch2
        while True:
          ch2 = Menu2()
          if ch2 == 1:
            quan = int(input("Enter Quantity : "))
            s = "Small"   #Size
            p = 420 
            fp = p * quan      #Final prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", pizza, ":", flav, s, "\t=>Price:", fp, "\n")
            name = "Tikka S P"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4)
            break
          elif ch2 == 2:
            quan = int(input("Enter Quantity : "))
            s = "Medium"   #Size
            p = 840
            fp = p * quan     #Final Prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", pizza, ":", flav, s, "\t=>Price:", fp, "\n")
            name = "Tikka Med P"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
          elif ch2 == 3:
            quan = int(input("Enter Quantity : "))
            s = "Large"   #Size
            p = 1190 
            fp = p * quan      #Final Prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", pizza, ":", flav, s, "\t=>Price:", fp, "\n")
            name = "Tikka L P"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
        break

      if ch1 == 3:
        flav = "Cheese"
        def Menu2():
          print("\t\t\t*-*-*-*-Pizza Size-*-*-*-*")
          print("\t1. Small (400)")
          print("\t2. Medium (750)")
          print("\t3. Large (1150)")
          ch2 = int(input("Enter Choice : "))
          return ch2
        while True:
          ch2 = Menu2()
          if ch2 == 1:
            quan = int(input("Enter Quantity : "))
            s = "Small"   #Size
            p = 400 
            fp = p * quan      #Final prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", pizza, ":", flav, s, "\t=>Price:", fp, "\n")
            name = "Cheese S P"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
          elif ch2 == 2:
            quan = int(input("Enter Quantity : "))
            s = "Medium"   #Size
            p = 750 
            fp = p * quan     #Final Prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", pizza, ":", flav, s, "\t=>Price:", fp, "\n")
            name = "Cheese Med P"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
          elif ch2 == 3:
            quan = int(input("Enter Quantity : "))
            s = "Large"   #Size
            p = 1150 
            fp = p * quan      #Final Prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", pizza, ":", flav, s, "\t=>Price:", fp, "\n")
            name = "Cheese L P"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4)
            break
        break        

      elif ch1 == 4:
        flav = "Special"
        def Menu2():
          print("\t\t\t*-*-*-*-Pizza Size-*-*-*-*")
          print("\t1. Small (500)")
          print("\t2. Medium (950)")
          print("\t3. Large (1300)")
          ch2 = int(input("Enter Choice : "))
          return ch2
        while True:
          ch2 = Menu2()
          if ch2 == 1:
            quan = int(input("Enter Quantity : "))
            s = "Small"   #Size
            p = 500 
            fp = p * quan      #Final prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", pizza, ":", flav, s, "\t=>Price:", fp, "\n")
            name = "Special S P"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
          elif ch2 == 2:
            quan = int(input("Enter Quantity : "))
            s = "Medium"   #Size
            p = 950 
            fp = p * quan     #Final Prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", pizza, ":", flav, s, "\t=>Price:", fp, "\n")
            name = "Special Med P"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
          elif ch2 == 3:
            quan = int(input("Enter Quantity : "))
            s = "Large"   #Size
            p = 1300
            fp = p * quan      #Final Prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", pizza, ":", flav, s, "\t=>Price:", fp, "\n")
            name = "Special L P"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
        break     
                                          #END OF PIZZA

  elif ch == 2:     #BURGERS
    bur = "Burgers"
    def Menu1():
      print("\t\t\t*-*-*-*-Burger Menu-*-*-*-*")
      print("\t1. Smasher Burger")
      print("\t2. Big Bang Burger")
      print("\t3. Cheese Stack Burger")
      print("\t4. Doppler")
      print("\t5. Dynamite")
      ch1 = int(input("Enter Choice : "))
      return ch1
    while True:
      ch1 = Menu1()
      if ch1 == 1:
        flav = "Smasher Burger"
        def Menu2():
          print("\t\t\t*-*-*-*-Burger Patty-*-*-*-*")
          print("\t1. Chicken (380)")
          print("\t2. Beef (595)")
          ch2 = int(input("Enter Choice : "))
          return ch2
        while True:
          ch2 = Menu2()
          if ch2 == 1:
            quan = int(input("Enter Quantity : "))
            s = "Chicken"   #Patty
            p = 380 
            fp = p * quan      #Final prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", bur, ":", flav, s, "\t=> Price:", fp, "\n")
            name = "Smasher CB"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
          elif ch2 == 2:
            quan = int(input("Enter Quantity : "))
            s = "Beef"   #Patty
            p = 595 
            fp = p * quan     #Final Prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", bur, ":", flav, s, "\t=> Price:", fp, "\n")
            name = "Smasher BB"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
        break

      elif ch1 == 2:
        flav = "Big Bang Burger"
        def Menu2():
          print("\t\t\t*-*-*-*-Burger Patty-*-*-*-*")
          print("\t1. Chicken (420)")
          print("\t2. Beef (560)")
          ch2 = int(input("Enter Choice : "))
          return ch2
        while True:
          ch2 = Menu2()
          if ch2 == 1:
            quan = int(input("Enter Quantity : "))
            s = "Chicken"   #Patty
            p = 420 
            fp = p * quan      #Final prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", bur, ":", flav, s, "\t=> Price:", fp, "\n")
            name = "Big Bang CB"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
          elif ch2 == 2:
            quan = int(input("Enter Quantity : "))
            s = "Beef"   #Patty
            p = 560 
            fp = p * quan     #Final Prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", bur, ":", flav, s, "\t=> Price:", fp, "\n")
            name = "Big Bang BB"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
        break

      elif ch1 == 3:
        flav = "Cheese Stack Burger"
        def Menu2():
          print("\t\t\t*-*-*-*-Burger Patty-*-*-*-*")
          print("\t1. Chicken (400)")
          print("\t2. Beef (580)")
          ch2 = int(input("Enter Choice : "))
          return ch2
        while True:
          ch2 = Menu2()
          if ch2 == 1:
            quan = int(input("Enter Quantity : "))
            s = "Chicken"   #Patty
            p = 400 
            fp = p * quan      #Final prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", bur, ":", flav, s, "\t=> Price:", fp, "\n")
            name = "Cheese S CB"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
          elif ch2 == 2:
            quan = int(input("Enter Quantity : "))
            s = "Beef"   #Patty
            p = 580
            fp = p * quan     #Final Prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", bur, ":", flav, s, "\t=> Price:", fp, "\n")
            name = "Cheese S BB"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
        break
    
      elif ch1 == 4:
        flav = "Doppler Burger"
        def Menu2():
          print("\t\t\t*-*-*-*-Burger Patty-*-*-*-*")
          print("\t1. Chicken (600)")
          print("\t2. Beef (900)")
          ch2 = int(input("Enter Choice : "))
          return ch2
        while True:
          ch2 = Menu2()
          if ch2 == 1:
            quan = int(input("Enter Quantity : "))
            s = "Chicken"   #Patty
            p = 600 
            fp = p * quan      #Final prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", bur, ":", flav, s, "\t=> Price:", fp, "\n")
            name = "Doppler CB"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
          elif ch2 == 2:
            quan = int(input("Enter Quantity : "))
            s = "Beef"   #Patty
            p = 900 
            fp = p * quan     #Final Prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", bur, ":", flav, s, "\t=> Price:", fp, "\n")
            name = "Doppler BB"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
        break
 
      elif ch1 == 5:
        flav = "Dynamite Burger"
        def Menu2():
          print("\t\t\t*-*-*-*-Burger Patty-*-*-*-*")
          print("\t1. Chicken (780)")
          print("\t2. Beef (980)")
          ch2 = int(input("Enter Choice : "))
          return ch2
        while True:
          ch2 = Menu2()
          if ch2 == 1:
            quan = int(input("Enter Quantity : "))
            s = "Chicken"   #Patty
            p = 780
            fp = p * quan      #Final prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", bur, ":", flav, s, "\t=> Price:", fp, "\n")
            name = "Dyna CB"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
          elif ch2 == 2:
            quan = int(input("Enter Quantity : "))
            s = "Beef"   #Patty
            p = 980 
            fp = p * quan     #Final Prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", bur, ":", flav, s, "\t=> Price:", fp, "\n")
            name = "Dyna BB"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
        break
                                        #END OF BURGERS

  elif ch == 3:     #FRIES
    fri = "Fries"
    def Menu1():
      print("\t\t\t*-*-*-*-Fries Menu-*-*-*-*")
      print("\t1. Small Fries (120)")
      print("\t2. Large Fries (290)")
      print("\t3. Peri Peri Fries (380)")
      print("\t4. Loaded Fries (490)")
      ch1 = int(input("Enter Choice : "))
      return ch1
    while True:
      ch1 = Menu1()
      if ch1 == 1:
        flav = "Small Fries"
        quan = int(input("Enter Quantity : "))
        s = "Small"   #Flavour
        p = 120 
        fp = p * quan      #Final prices
        print("\n\t*-*-Order Placed-*-*\n")
        print(quan, "x", fri, ":", s, "\t=> Price:", fp, "\n")
        name = "Small F"
        queue1.enque(name)    #Added in queue1
        queue2.enque(quan)    #Added in queue2
        queue3.enque(p)       #Added in queue3
        queue4.enque(fp)      #Added in queue4
        break

      elif ch1 == 2:
        flav = "Large Fries"
        quan = int(input("Enter Quantity : "))
        s = "Large"   #Flavour
        p = 290 
        fp = p * quan      #Final prices
        print("\n\t*-*-Order Placed-*-*\n")
        print(quan, "x", fri, ":", s, "\t=> Price:", fp, "\n")
        name = "Large F"
        queue1.enque(name)    #Added in queue1
        queue2.enque(quan)    #Added in queue2
        queue3.enque(p)       #Added in queue3
        queue4.enque(fp)      #Added in queue4
        break

      elif ch1 == 3:
        flav = "Peri Peri Fries"
        quan = int(input("Enter Quantity : "))
        s = "Peri Peri"   #Flavour
        p = 380 
        fp = p * quan      #Final prices
        print("\n\t*-*-Order Placed-*-*\n")
        print(quan, "x", fri, ":", s, "\t=> Price:", fp, "\n")
        name = "Peri Peri F"
        queue1.enque(name)    #Added in queue1
        queue2.enque(quan)    #Added in queue2
        queue3.enque(p)       #Added in queue3
        queue4.enque(fp)      #Added in queue4
        break

      elif ch1 == 4:
        flav = "Loaded Fries"
        quan = int(input("Enter Quantity : "))
        s = "Loaded"   #Flavour
        p = 490
        fp = p * quan      #Final prices
        print("\n\t*-*-Order Placed-*-*\n")
        print(quan, "x", fri, ":", s, "\t=> Price:", fp, "\n")
        name = "Loaded F"
        queue1.enque(name)    #Added in queue1
        queue2.enque(quan)    #Added in queue2
        queue3.enque(p)       #Added in queue3
        queue4.enque(fp)      #Added in queue4
        break
      break
                                    #END OF FRIES

  elif ch == 4:     #DESERTS
    des = "Desserts"
    def Menu1():
      print("\t\t\t*-*-*-*-Desserts Menu-*-*-*-*")
      print("\t1. Molten Lava Cake (550)")
      print("\t2. Cheese Cake (300)")
      print("\t3. Cocoa Brownies (380)")
      print("\t4. ChocoChip Cookies (220)")
      print("\t5. Donuts (150)")
      print("\t6. Ice Cream (Per Scoop 180)")
      ch1 = int(input("Enter Choice : "))
      return ch1
    while True:
      ch1 = Menu1()
      if ch1 == 1:
        flav = "Molten Lava"
        quan = int(input("Enter Quantity : "))
        s = "Cake"   #Type
        p = 550 
        fp = p * quan      #Final prices
        print("\n\t*-*-Order Placed-*-*\n")
        print(quan, "x", des, ":", flav, s, "\t=> Price:", fp, "\n")
        name = "Molten Lava C"
        queue1.enque(name)    #Added in queue1
        queue2.enque(quan)    #Added in queue2
        queue3.enque(p)       #Added in queue3
        queue4.enque(fp)      #Added in queue4
        break

      elif ch1 == 2:
        flav = "Cheese"
        quan = int(input("Enter Quantity : "))
        s = "Cake"   #Type
        p = 300 
        fp = p * quan      #Final prices
        print("\n\t*-*-Order Placed-*-*\n")
        print(quan, "x",  des, ":", flav, s, "\t=> Price:", fp, "\n")
        name = "Cheese C"
        queue1.enque(name)    #Added in queue1
        queue2.enque(quan)    #Added in queue2
        queue3.enque(p)       #Added in queue3
        queue4.enque(fp)      #Added in queue4
        break

      elif ch1 == 3:
        flav = "Cocoa"
        quan = int(input("Enter Quantity : "))
        s = "Brownies"   #Type
        p = 380 
        fp = p * quan      #Final prices
        print("\n\t*-*-Order Placed-*-*\n")
        print(quan, "x", des, ":", flav, s, "\t=> Price:", fp, "\n")
        name = "Cocoa B"
        queue1.enque(name)    #Added in queue1
        queue2.enque(quan)    #Added in queue2
        queue3.enque(p)       #Added in queue3
        queue4.enque(fp)      #Added in queue4
        break

      elif ch1 == 4:
        flav = "Chocolate Chip"
        quan = int(input("Enter Quantity : "))
        s = "Cookies"   #Type
        p = 220 
        fp = p * quan      #Final prices
        print("\n\t*-*-Order Placed-*-*\n")
        print(quan, "x", des, ":", flav, s, "\t=> Price:", fp, "\n")
        name = "ChocoChip C"
        queue1.enque(name)    #Added in queue1
        queue2.enque(quan)    #Added in queue2
        queue3.enque(p)       #Added in queue3
        queue4.enque(fp)      #Added in queue4
        break

      elif ch1 == 5:
        flav = "Donuts"
        quan = int(input("Enter Quantity : "))
        s = "Donuts"   #Type
        p = 150
        fp = p * quan      #Final prices
        print("\n\t*-*-Order Placed-*-*\n")
        print(quan, "x", des, ":", flav, s, "\t=> Price:", fp, "\n")
        name = "Donuts"
        queue1.enque(name)    #Added in queue1
        queue2.enque(quan)    #Added in queue2
        queue3.enque(p)       #Added in queue3
        queue4.enque(fp)      #Added in queue4
        break

      elif ch1 == 6:
        flav = "Ice"
        quan = int(input("Enter Quantity : "))
        s = "Cream "   #Type
        p = 180
        fp = p * quan      #Final prices
        print("\n\t*-*-Order Placed-*-*\n")
        print(quan, "x", des, ":", flav, s, "\t=> Price:", fp, "\n")
        name = "Ice Cream "
        queue1.enque(name)    #Added in queue1
        queue2.enque(quan)    #Added in queue2
        queue3.enque(p)       #Added in queue3
        queue4.enque(fp)      #Added in queue4)
        break
      break
                                                #END OF DESSERTS MENU

  elif ch == 5:     #DRINKS
    dri = "Drinks"
    def Menu1():
      print("\t\t\t*-*-*-*-Drink Menu-*-*-*-*")
      print("\t1. Shakes")
      print("\t2. Soft Drinks")
      print("\t3. Fresh Juices")
      print("\t4. Coffee")
      print("\t5. Tea")
      ch1 = int(input("Enter Choice : "))
      return ch1
    while True:
      ch1 = Menu1()
      if ch1 == 1:        #SHAKE MENU
        def Menu2():
          print("\t\t\t*-*-*-*-Shakes Menu-*-*-*-*")
          print("\t1. Oreo Shake (300)")
          print("\t2. Vanilla Shake (250)")
          print("\t3. Cookies and Cream Milkshake (280)")
          print("\t4. Mango Milkshake (220)")
          print("\t5. Banana Milkshake (200)")
          ch2 = int(input("Enter Choice : "))
          return ch2
        while True:
          typ = "Shake"
          ch2 = Menu2()
          if ch2 == 1:
            flav = "Oreo Shake"
            quan = int(input("Enter Quantity : "))
            p = 300 
            fp = p * quan      #Final prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", typ, ":", flav, "\t=>Price:", fp, "\n")
            name = "Oreo S"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
          elif ch2 == 2:
            flav = "Vanilla Shake"
            quan = int(input("Enter Quantity : "))
            p = 250 
            fp = p * quan      #Final prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", typ, ":", flav, "\t=>Price:", fp, "\n")
            name = "Vanilla S"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
          elif ch2 == 3:
            flav = "Cookies and Cream Milkshake"
            quan = int(input("Enter Quantity : "))
            p = 280 
            fp = p* quan      #Final prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", typ, ":", flav, "\t=>Price:", fp, "\n")
            name = "Cookies_C MS"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
          elif ch2 == 4:
            flav = "Mango Milkshake"
            quan = int(input("Enter Quantity : "))
            p = 220 
            fp = p * quan      #Final prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", typ, ":", flav, "\t=>Price:", fp, "\n")
            name = "Mango MS"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
          elif ch2 == 5:
            flav = "Banana Milkshake"
            quan = int(input("Enter Quantity : "))
            p = 200 
            fp = p * quan      #Final prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", typ, ":", flav, "\t=>Price:", fp, "\n")
            name = "Banana MS"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
        break                       #END OF SHAKE MENU

      elif ch1 == 2:          #SOFT DRINK MENU
        def Menu2():
          print("\t\t\t*-*-*-*-Soft Drinks Menu-*-*-*-*")
          print("\t1. Pepsi ")
          print("\t2. Coca Cola")
          print("\t3. 7 Up")
          print("\t4. Sprite")
          print("\t5. Mountain Dew")
          ch2 = int(input("Enter Choice : "))
          return ch2
        while True:
          ch2 = Menu2()
          if ch2 == 1:
            flav = "Soft Drink"
            def Menu2():
              print("\t\t\t*-*-*-*-Drink Size-*-*-*-*")
              print("\t1. 500ml (100)")
              print("\t2. 1.5L (150)")
              print("\t3. 2.25L (220)")
              ch2 = int(input("Enter Choice : "))
              return ch2
            while True:
              ch2 = Menu2()
              if ch2 == 1:
                quan = int(input("Enter Quantity : "))
                s = "Pepsi "   #name
                p = 100 
                fp = p * quan      #Final prices
                print("\n\t*-*-Order Placed-*-*\n")
                print(quan, "x", flav, ":", s, "\t=>Price:", fp, "\n")
                name = "Pepsi "
                queue1.enque(name)    #Added in queue1
                queue2.enque(quan)    #Added in queue2
                queue3.enque(p)       #Added in queue3
                queue4.enque(fp)      #Added in queue4
                break
              elif ch2 == 2:
                quan = int(input("Enter Quantity : "))
                s = "Pepsi 1.5L"   #name
                p = 150 
                fp = p * quan     #Final Prices
                print("\n\t*-*-Order Placed-*-*\n")
                print(quan, "x", flav, ":", s, "\t=>Price:", fp, "\n")
                name = "Pepsi "
                queue1.enque(name)    #Added in queue1
                queue2.enque(quan)    #Added in queue2
                queue3.enque(p)       #Added in queue3
                queue4.enque(fp)      #Added in queue4
                break
              elif ch2 == 3:
                quan = int(input("Enter Quantity : "))
                s = "Pepsi"   #name
                p = 220 
                fp = p * quan     #Final Prices
                print("\n\t*-*-Order Placed-*-*\n")
                print(quan, "x", flav, ":", s, "\t=>Price:", fp, "\n")
                name = "Pepsi"
                queue1.enque(name)    #Added in queue1
                queue2.enque(quan)    #Added in queue2
                queue3.enque(p)       #Added in queue3
                queue4.enque(fp)      #Added in queue4
                break
            break
        
          elif ch2 == 2:
            flav = "Soft Drink"
            def Menu2():
              print("\t\t\t*-*-*-*-Drink Size-*-*-*-*")
              print("\t1. 500ml (100)")
              print("\t2. 1.5L (150)")
              print("\t3. 2.25L (220)")
              ch2 = int(input("Enter Choice : "))
              return ch2
            while True:
              ch2 = Menu2()
              if ch2 == 1:
                quan = int(input("Enter Quantity : "))
                s = "Coca Cola"   #name
                p = 100 
                fp = p * quan      #Final prices
                print("\n\t*-*-Order Placed-*-*\n")
                print(quan, "x", flav, ":", s, "\t=>Price:", fp, "\n")
                name = "Coca Cola"
                queue1.enque(name)    #Added in queue1
                queue2.enque(quan)    #Added in queue2
                queue3.enque(p)       #Added in queue3
                queue4.enque(fp)      #Added in queue4
                break
              elif ch2 == 2:
                quan = int(input("Enter Quantity : "))
                s = "Coca Cola 1.5L"   #name
                p = 150 
                fp = p * quan     #Final Prices
                print("\n\t*-*-Order Placed-*-*\n")
                print(quan, "x", flav, ":", s, "\t=>Price:", fp, "\n")
                name = "Coca Cola"
                queue1.enque(name)    #Added in queue1
                queue2.enque(quan)    #Added in queue2
                queue3.enque(p)       #Added in queue3
                queue4.enque(fp)      #Added in queue4
                break
              elif ch2 == 3:
                quan = int(input("Enter Quantity : "))
                s = "Coca Cola 2.25L"   #name
                p = 220 
                fp = p * quan     #Final Prices
                print("\n\t*-*-Order Placed-*-*\n")
                print(quan, "x", flav, ":", s, "\t=>Price:", fp, "\n")
                name = "Coca Cola"
                queue1.enque(name)    #Added in queue1
                queue2.enque(quan)    #Added in queue2
                queue3.enque(p)       #Added in queue3
                queue4.enque(fp)      #Added in queue4
                break
            break
        
          elif ch2 == 3:
              flav = "Soft Drink"
              def Menu2():
                print("\t\t\t*-*-*-*-Drink Size-*-*-*-*")
                print("\t1. 500ml (100)")
                print("\t2. 1.5L (150)")
                print("\t3. 2.25L (220)")
                ch2 = int(input("Enter Choice : "))
                return ch2
              while True:
                ch2 = Menu2()
                if ch2 == 1:
                  quan = int(input("Enter Quantity : "))
                  s = "7 Up 500ml"   #name
                  p = 100 
                  fp = p * quan      #Final prices
                  print("\n\t*-*-Order Placed-*-*\n")
                  print(quan, "x", flav, ":", s, "\t=>Price:", fp, "\n")
                  name = "7 Up"
                  queue1.enque(name)    #Added in queue1
                  queue2.enque(quan)    #Added in queue2
                  queue3.enque(p)       #Added in queue3
                  queue4.enque(fp)      #Added in queue4
                  break
                elif ch2 == 2:
                  quan = int(input("Enter Quantity : "))
                  s = "7 Up 1.5L"   #name
                  p = 150 
                  fp = p * quan     #Final Prices
                  print("\n\t*-*-Order Placed-*-*\n")
                  print(quan, "x",flav, ":", s, "\t=>Price:", fp, "\n")
                  name = "7 Up"
                  queue1.enque(name)    #Added in queue1
                  queue2.enque(quan)    #Added in queue2
                  queue3.enque(p)       #Added in queue3
                  queue4.enque(fp)      #Added in queue4
                  break
                elif ch2 == 3:
                  quan = int(input("Enter Quantity : "))
                  s = "7 Up 2.25L"   #name
                  p = 220 
                  fp = p * quan     #Final Prices
                  print("\n\t*-*-Order Placed-*-*\n")
                  print(quan, "x", flav, ":", s, "\t=>Price:", fp, "\n")
                  name = "7 Up"
                  queue1.enque(name)    #Added in queue1
                  queue2.enque(quan)    #Added in queue2
                  queue3.enque(p)       #Added in queue3
                  queue4.enque(fp)      #Added in queue4
                  break
              break
          
          elif ch2 == 4:
            flav = "Soft Drink"
            def Menu2():
              print("\t\t\t*-*-*-*-Drink Size-*-*-*-*")
              print("\t1. 500ml (100)")
              print("\t2. 1.5L (150)")
              print("\t3. 2.25L (220)")
              ch2 = int(input("Enter Choice : "))
              return ch2
            while True:
              ch2 = Menu2()
              if ch2 == 1:
                quan = int(input("Enter Quantity : "))
                s = "Sprite 500ml"   #name
                p = 100
                fp = p  * quan      #Final prices
                print("\n\t*-*-Order Placed-*-*\n")
                print(quan, "x", flav, ":", s, "\t=>Price:", fp, "\n")
                name = "Sprite"
                queue1.enque(name)    #Added in queue1
                queue2.enque(quan)    #Added in queue2
                queue3.enque(p)       #Added in queue3
                queue4.enque(fp)      #Added in queue4
                break
              elif ch2 == 2:
                quan = int(input("Enter Quantity : "))
                s = "Sprite 1.5L"   #name
                p = 150 
                fp = p * quan     #Final Prices
                print("\n\t*-*-Order Placed-*-*\n")
                print(quan, "x", flav, ":", s, "\t=>Price:", fp, "\n")
                name = "Sprite"
                queue1.enque(name)    #Added in queue1
                queue2.enque(quan)    #Added in queue2
                queue3.enque(p)       #Added in queue3
                queue4.enque(fp)      #Added in queue4
                break
              elif ch2 == 3:
                quan = int(input("Enter Quantity : "))
                s = "Sprite 2.25L"   #name
                p = 220 
                fp = p * quan     #Final Prices
                print("\n\t*-*-Order Placed-*-*\n")
                print(quan, "x", flav, ":", s, "\t=>Price:", fp, "\n")
                name = "Sprite "
                queue1.enque(name)    #Added in queue1
                queue2.enque(quan)    #Added in queue2
                queue3.enque(p)       #Added in queue3
                queue4.enque(fp)      #Added in queue4
                break
            break
        
          elif ch2 == 5:
            flav = "Soft Drink"
            def Menu2():
              print("\t\t\t*-*-*-*-Drink Size-*-*-*-*")
              print("\t1. 500ml (100)")
              print("\t2. 1.5L (150)")
              print("\t3. 2.25L (220)")
              ch2 = int(input("Enter Choice : "))
              return ch2
            while True:
              ch2 = Menu2()
              if ch2 == 1:
                quan = int(input("Enter Quantity : "))
                s = "Mountain Dew 500ml"   #name
                p = 100 
                fp = p * quan      #Final prices
                print("\n\t*-*-Order Placed-*-*\n")
                print(quan, "x", flav, ":", s, "\t=>Price:", fp, "\n")
                name = "M Dew"
                queue1.enque(name)    #Added in queue1
                queue2.enque(quan)    #Added in queue2
                queue3.enque(p)       #Added in queue3
                queue4.enque(fp)      #Added in queue4
                break
              elif ch2 == 2:
                quan = int(input("Enter Quantity : "))
                s = "Mountain Dew 1.5L"   #name
                p = 150
                fp = p * quan     #Final Prices
                print("\n\t*-*-Order Placed-*-*\n")
                print(quan, "x",flav, ":", s, "\t=>Price:", fp, "\n")
                name = "M Dew"
                queue1.enque(name)    #Added in queue1
                queue2.enque(quan)    #Added in queue2
                queue3.enque(p)       #Added in queue3
                queue4.enque(fp)      #Added in queue4
                break
              elif ch2 == 3:
                quan = int(input("Enter Quantity : "))
                s = "Mountain Dew 2.25L"   #name
                p = 220 
                fp = p * quan     #Final Prices
                print("\n\t*-*-Order Placed-*-*\n")
                print(quan, "x", flav, ":", s, "\t=>Price:", fp, "\n")
                name = "M Dew"
                queue1.enque(name)    #Added in queue1
                queue2.enque(quan)    #Added in queue2
                queue3.enque(p)       #Added in queue3
                queue4.enque(fp)      #Added in queue4
                break
            break
        break                             #END OF SOFT DRINKS

      elif ch1 == 3:        #FRESH JUICE MENU
        def Menu2():
          print("\t\t\t*-*-*-*-Fresh Juices Menu-*-*-*-*")
          print("\t1. Apple")
          print("\t2. Orange")
          print("\t3. Pomegranate")
          print("\t4. Pineapple")
          print("\t5. Craneberry")
          ch2 = int(input("Enter Choice : "))
          return ch2
        while True:
          ch2 = Menu2()
          if ch2 == 1:
            flav = "Fresh Juice"
            def Menu2():
              print("\t\t\t*-*-*-*-Juice Size-*-*-*-*")
              print("\t1. 250 ml (100)")
              print("\t2. 500 ml (180)")
              ch2 = int(input("Enter Choice : "))
              return ch2
            while True:
              ch2 = Menu2()
              if ch2 == 1:
                quan = int(input("Enter Quantity : "))
                s = "Apple Juice"   #flav
                p = 100 
                fp = p * quan      #Final prices
                print("\n\t*-*-Order Placed-*-*\n")
                print(quan, "x", flav, ":", s, "\t=> Price:", fp, "\n")
                name = "Apple J"
                queue1.enque(name)    #Added in queue1
                queue2.enque(quan)    #Added in queue2
                queue3.enque(p)       #Added in queue3
                queue4.enque(fp)      #Added in queue4
                break
              elif ch2 == 2:
                quan = int(input("Enter Quantity : "))
                s = "Apple Juice"   #flav
                p = 180 
                fp = p * quan     #Final Prices
                print("\n\t*-*-Order Placed-*-*\n")
                print(quan, "x", flav, ":", s, "\t=> Price:", fp, "\n")
                name = "Apple J"
                queue1.enque(name)    #Added in queue1
                queue2.enque(quan)    #Added in queue2
                queue3.enque(p)       #Added in queue3
                queue4.enque(fp)      #Added in queue4
                break
            break
          elif ch2 == 2:
            flav = "Fresh Juice"
            def Menu2():
              print("\t\t\t*-*-*-*-Juice Size-*-*-*-*")
              print("\t1. 250 ml (100)")
              print("\t2. 500 ml (180)")
              ch2 = int(input("Enter Choice : "))
              return ch2
            while True:
              ch2 = Menu2()
              if ch2 == 1:
                quan = int(input("Enter Quantity : "))
                s = "Orange Juice"   #flav
                p = 100 
                fp = p * quan      #Final prices
                print("\n\t*-*-Order Placed-*-*\n")
                print(quan, "x", flav, ":", s, "\t=> Price:", fp, "\n")
                name = "Orange J"
                queue1.enque(name)    #Added in queue1
                queue2.enque(quan)    #Added in queue2
                queue3.enque(p)       #Added in queue3
                queue4.enque(fp)      #Added in queue4
                break
              elif ch2 == 2:
                quan = int(input("Enter Quantity : "))
                s = "Orange Juice"   #flav
                p = 180
                fp = p * quan     #Final Prices
                print("\n\t*-*-Order Placed-*-*\n")
                print(quan, "x", flav, ":", s, "\t=> Price:", fp, "\n")
                name = "Orange J "
                queue1.enque(name)    #Added in queue1
                queue2.enque(quan)    #Added in queue2
                queue3.enque(p)       #Added in queue3
                queue4.enque(fp)      #Added in queue4
                break
            break
          elif ch2 == 3:
            flav = "Fresh Juice"
            def Menu2():
              print("\t\t\t*-*-*-*-Juice Size-*-*-*-*")
              print("\t1. 250 ml (100)")
              print("\t2. 500 ml (180)")
              ch2 = int(input("Enter Choice : "))
              return ch2
            while True:
              ch2 = Menu2()
              if ch2 == 1:
                quan = int(input("Enter Quantity : "))
                s = "Pomegranate Juice"   #flav
                p = 100 
                fp = p * quan      #Final prices
                print("\n\t*-*-Order Placed-*-*\n")
                print(quan, "x", flav, ":", s, "\t=> Price:", fp, "\n")
                name = "Pomegranate J"
                queue1.enque(name)    #Added in queue1
                queue2.enque(quan)    #Added in queue2
                queue3.enque(p)       #Added in queue3
                queue4.enque(fp)      #Added in queue4
                break
              elif ch2 == 2:
                quan = int(input("Enter Quantity : "))
                s = "Pomegranate Juice"   #flav
                p = 180
                fp = p * quan     #Final Prices
                print("\n\t*-*-Order Placed-*-*\n")
                print(quan, "x", flav, ":", s, "\t=> Price:", fp, "\n")
                name = "Pomegranate J"
                queue1.enque(name)    #Added in queue1
                queue2.enque(quan)    #Added in queue2
                queue3.enque(p)       #Added in queue3
                queue4.enque(fp)      #Added in queue4
                break
            break
          elif ch2 == 4:
            flav = "Fresh Juice"
            def Menu2():
              print("\t\t\t*-*-*-*-Juice Size-*-*-*-*")
              print("\t1. 250 ml (100)")
              print("\t2. 500 ml (180)")
              ch2 = int(input("Enter Choice : "))
              return ch2
            while True:
              ch2 = Menu2()
              if ch2 == 1:
                quan = int(input("Enter Quantity : "))
                s = "Pineapple Juice"   #flav
                p = 100 
                fp = p * quan      #Final prices
                print("\n\t*-*-Order Placed-*-*\n")
                print(quan, "x", flav, ":", s, "\t=> Price:", fp, "\n")
                name = "Pineapple J"
                queue1.enque(name)    #Added in queue1
                queue2.enque(quan)    #Added in queue2
                queue3.enque(p)       #Added in queue3
                queue4.enque(fp)      #Added in queue4
                break
              elif ch2 == 2:
                quan = int(input("Enter Quantity : "))
                s = "Pineapple Juice"   #flav
                p = 180
                fp = p * quan     #Final Prices
                print("\n\t*-*-Order Placed-*-*\n")
                print(quan, "x", flav, ":", s, "\t=> Price:", fp, "\n")
                name = "Pineapple J"
                queue1.enque(name)    #Added in queue1
                queue2.enque(quan)    #Added in queue2
                queue3.enque(p)       #Added in queue3
                queue4.enque(fp)      #Added in queue4
                break
            break
          elif ch2 == 5:
            flav = "Fresh Juice"
            def Menu2():
              print("\t\t\t*-*-*-*-Juice Size-*-*-*-*")
              print("\t1. 250 ml (100)")
              print("\t2. 500 ml (180)")
              ch2 = int(input("Enter Choice : "))
              return ch2
            while True:
              ch2 = Menu2()
              if ch2 == 1:
                quan = int(input("Enter Quantity : "))
                s = "Craneberry Juice"   #flav
                p = 100 
                fp = p * quan      #Final prices
                print("\n\t*-*-Order Placed-*-*\n")
                print(quan, "x", flav, ":", s, "\t=> Price:", fp, "\n")
                name = "Craneberry J"
                queue1.enque(name)    #Added in queue1
                queue2.enque(quan)    #Added in queue2
                queue3.enque(p)       #Added in queue3
                queue4.enque(fp)      #Added in queue4
                break
              elif ch2 == 2:
                quan = int(input("Enter Quantity : "))
                s = "Craneberry Juice"   #flav
                p = 180
                fp = p * quan     #Final Prices
                print("\n\t*-*-Order Placed-*-*\n")
                print(quan, "x", flav, ":", s, "\t=> Price:", fp, "\n")
                name = "Craneberry J"
                queue1.enque(name)    #Added in queue1
                queue2.enque(quan)    #Added in queue2
                queue3.enque(p)       #Added in queue3
                queue4.enque(fp)      #Added in queue4
                break
            break
        break               #END OF FRESH JUICE

      elif ch1 == 4:      #COFFEE MENU   
        def Menu2():
          print("\t\t\t*-*-*-*-Coffee Menu-*-*-*-*")
          print("\t1. Espresso (480)")
          print("\t2. Cappuccino (280)")
          print("\t3. Mocha (300)")
          print("\t4. Iced Coffee (250)")
          print("\t5. Latte (450)")
          ch2 = int(input("Enter Choice : "))
          return ch2
        while True:
          flav = "Coffe"
          ch2 = Menu2()
          if ch2 == 1:
            quan = int(input("Enter Quantity : "))
            s = "Espresso"   #flav
            p = 480 
            fp = p * quan      #Final prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", flav, ":", s, "\t=> Price:", fp, "\n")
            name = "Espresso C"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
          elif ch2 == 2:
            quan = int(input("Enter Quantity : "))
            s = "Cappuccino"   #flav
            p = 280 
            fp = p * quan     #Final Prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", flav, ":", s, "\t=> Price:", fp, "\n")
            name = "Cappuccino C"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
          elif ch2 == 3:
            quan = int(input("Enter Quantity : "))
            s = "Mocha"   #flav
            p = 300 
            fp = p * quan     #Final Prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", flav, ":", s, "\t=> Price:", fp, "\n")
            name = "Mocha C"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
          elif ch2 == 4:
            quan = int(input("Enter Quantity : "))
            s = "Iced Coffee"   #flav
            p = 250 
            fp = p * quan     #Final Prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", flav, ":", s, "\t=> Price:", fp, "\n")
            name = "Iced C"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
          elif ch2 == 5:
            quan = int(input("Enter Quantity : "))
            s = "Latte"   #flav
            p = 450 
            fp = p * quan     #Final Prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", flav, ":", s, "\t=> Price:", fp, "\n")
            name = "Latte C"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
        break               #END OF COFFEE

      elif ch1 == 5:      #TEA MENU  
        def Menu2():
          print("\t\t\t*-*-*-*-Tea Menu-*-*-*-*")
          print("\t1. Black Tea (250)")
          print("\t2. Green Tea (150)")
          print("\t3. Herbal Tea (200)")
          print("\t4. Pyala Chai(120)")
          ch2 = int(input("Enter Choice : "))
          return ch2
        while True:
          flav = "Tea"
          ch2 = Menu2()
          if ch2 == 1:
            quan = int(input("Enter Quantity : "))
            s = "Black Tea"   #flav
            p = 250 
            fp = p * quan      #Final prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", flav, ":", s, "\t=> Price:", fp, "\n")
            name = "Black T"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
          elif ch2 == 2: 
            quan = int(input("Enter Quantity : "))
            s = "Green Tea"   #flav
            p = 150 
            fp = p * quan      #Final prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", flav, ":", s, "\t=> Price:", fp, "\n")
            name = "Green T"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break
          elif ch2 == 3: 
            quan = int(input("Enter Quantity : "))
            s = "Herbal Tea"   #flav
            p = 200 
            fp = p * quan      #Final prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", flav, ":", s, "\t=> Price:", fp, "\n")
            name = "Herbal T"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break   
          elif ch2 == 4: 
            quan = int(input("Enter Quantity : "))
            s = "Pyala Chai"   #flav
            p = 120 
            fp = p * quan      #Final prices
            print("\n\t*-*-Order Placed-*-*\n")
            print(quan, "x", flav, ":", s, "\t=> Price:", fp, "\n")
            name = "Pyala T"
            queue1.enque(name)    #Added in queue1
            queue2.enque(quan)    #Added in queue2
            queue3.enque(p)       #Added in queue3
            queue4.enque(fp)      #Added in queue4
            break   
        break       #END OF TEA

                                  #END OF DRINKS

  elif ch == 6:
    check()       #Calls check order func
  
  elif ch == 7:
    payment()     #Calls payment func
    break

  elif ch == 0:
    exit()      #Calls exit func
    break